### ISSUE TITLE
Email share has title twice in the subject line

### ISSUE THREAD

**Issue by farmerpaul** [wcoder/share-buttons#19]
When you click an email share button, the email that's composed has a subject line with the page title displayed twice in a row, separated by a slash.

I'm not sure what the intention was for positions `{0}` and `{1}` in the `MAIL_LINK_FORMAT` string, but the code that generates the email link inserts URL-escaped `title` with a slash appended to it for `{0}`, and immediately follows it with the non-escaped `titleDef`. This results in the title appearing twice in the subject line. I'm surprised nobody else has noticed this?

Seems to me that `MAIL_LINK_FORMAT` should instead just have one substitution for the subject line `{0}`, being `title`. Thoughts?

**Comment by yauhenipakala** [comment]
@farmerpaul Thank you for the report! Yes, you are right!
Fixed.
Could you please check?
